import adapterNode from '@sveltejs/adapter-node';
import adapterStatic from '@sveltejs/adapter-static';

// FREEZE PATH.
// During the semester the site runs on Adam's box under adapter-node, because
// /api/submit, /api/assistant and the studio-twin ingest all need a server.
// In December we set SMT_MODE=archive, which swaps in adapter-static and
// prerenders everything. Nothing in src/routes outside /api may depend on a
// server-only load, or that swap breaks. `npm run audit:freeze` checks it.
const archive = process.env.SMT_MODE === 'archive';

export default {
  kit: {
    adapter: archive
      ? adapterStatic({ pages: 'build', assets: 'build', fallback: null, precompress: false, strict: false })
      : adapterNode({ out: 'build' }),
    prerender: {
      // Cover images are generated by `npm run covers` against a running
      // server, so they are legitimately absent at build time.
      handleHttpError: ({ path, message }) =>
        path.startsWith('/covers/') || path.startsWith('/submissions/') || path.startsWith('/boards/')
          ? null
          : console.warn(message),
      // A route with no content yet (no assignments written, no submissions in)
      // is normal during the build-out, not an error.
      handleUnseenRoutes: 'ignore',
      // /api is server-only and never prerenders. In archive mode the routes
      // are excluded from the build entirely (see src/routes/api/+layout.js).
      entries: ['*']
    },
    alias: {
      $content: 'src/content'
    }
  }
};
